Escape dollar

diff --git a/.github/workflows/git-whitespace.yml b/.github/workflows/git-whitespace.yml
--- a/.github/workflows/git-whitespace.yml
+++ b/.github/workflows/git-whitespace.yml
@@ -71,6 +71,12 @@ jobs:
 
         names=\$( git diff --cached --name-only --diff-filter=AM  \$against | grep -vE "\${exclude_regex}" )
 
+        if [ \$? -ne 0 ]; then
+            echo "Error running git diff command"
+            echo "Error running git diff command" >>/scratch/art-daq/build.log
+            exit 1
+        fi
+
         rc=0
         IFS_SAVE=\$IFS
         IFS=\$'\\n'
