Abort job if CMake fails

diff --git a/.github/workflows/otsdaq-test-single-pkg.yml b/.github/workflows/otsdaq-test-single-pkg.yml
--- a/.github/workflows/otsdaq-test-single-pkg.yml
+++ b/.github/workflows/otsdaq-test-single-pkg.yml
@@ -98,6 +98,12 @@ jobs:
         echo "Configuring with cmake --preset default /scratch/art-daq/\$REPO -DCMAKE_CXX_COMPILER=\$compiler -Wno-dev"
         cmake --preset default /scratch/art-daq/\$REPO -DCMAKE_CXX_COMPILER=\$compiler -Wno-dev
 
+        res=\$?
+        if [ \$res -ne 0 ]; then
+            echo "CMake configuration failed with status code \$res"
+            echo "CMake configuration failed with status code \$res" >>/scratch/art-daq/build.log
+            exit \$res
+        fi
         echo "Compiling code"
         make -j\$CETPKG_J 2>&1 | tee -a /scratch/art-daq/build.log
         res=\${PIPESTATUS[0]} # Get result of first command in previous pipe, bash specific
